export const FECTCH_USER_CART = 'FETCH_USER_CART';
export const DELETE_CART_PRODUCT = 'DELETE_CART_PRODUCT';
export const ADD_CART_PRODUCT = 'ADD_CART_PRODUCT';
export const CHANGE_QUANTITY_PRODUCT = 'CHANGE_QUANTITY_PRODUCT';
export const DELETE_CART = 'DELETE_CART';
